### ISSUE TITLE
  字符集 怎么来的，代码报错了

### ISSUE THREAD

**Issue by ljtlrh** [bojone/word-discovery#1]
vocab_file = 'wx.chars'  # 字符集

**Comment by ky941122** [comment]
> vocab_file = 'wx.chars' # 字符集

需要提前先编译好kenlm，这里都有写https://kexue.fm/archives/6920，用之前可以先看看。

**Comment by bojone** [comment]
wx.chars是字符集要保存的文件名，kenlm的count_ngrams会帮你生成。

**Comment by Heatherse** [comment]
你好，我想问下这边我kenlm已经装好了

cmake -Wno-dev ..
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
--   system
[ 98%
--   thread
--   unit_test_framework
--   chrono
--   date_time
--   atomic
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kit/kenlm/build

make -j 4
[ 98%] Built target corpus_count_test
[ 99%] Built target count_ngrams
[100%] Built target lmplz
[100%] Built target adjust_counts_test
上面是安装成功的提示，但是在用count_ngrams函数处理我的语料的时候，只生成一个空的ngram文件是为什么呢
