### ISSUE TITLE
关于total的理解为何是总字数？

### ISSUE THREAD

**Issue by TITC** [bojone/word-discovery#10]
以下代码摘自[【中文分词系列】 8. 更好的新词发现算法](https://kexue.fm/archives/4256/comment-page-4#%E4%BB%A3%E7%A0%81%E5%AE%9E%E7%8E%B0)
```python
    for t in texts(" is ngraming..."):
        for i in range(len(t)):
            for j in range(1, n + 1):  # gram 1,2,3···n
                if i + j <= len(t):  # prevent overflow the length of t
                    # ngram is a huge dict,key is the word and value is the count
                    ngrams[t[i:i + j]] += 1
```
以8字的例句`本刊感谢各位专家`为例，进行ngram分词后结果为一个大小为26的dict
![image](https://user-images.githubusercontent.com/35098797/132294771-8de02793-f358-45d6-b182-446b63539e77.png)
对于此问题，您给出了如下的解释：
>别忘了某个句子的全体ngram是
[text[i:i + n] for i in range(len(text) - n + 1)]
所以总ngram数约等于总字数。

考虑到也许您的约等于是指数量级上的约等于, 因此下面取几个大文件对比一下

1. 总字符数为`234958742`字,ngram中所有key的频次累加和为`736195698`
2. 总字符数为`202362720`字,ngram中所有key的频次累加和为`624372458`
3. 总字符数为`110199596`字,ngram中所有key的频次累加和为`346968516`

由上述局部的`本刊感谢各位专家`例子亦或者是大文件的例子都可以看到ngram中频次累加和均大致为数据总字数的3倍左右。但3倍在计算PMI处理的过程中会带来多大差距呢？我以`1.`为例，取其中最高频次的词汇`企业`，频次`1307887`，其中`企`频次为`1953603`，`业`频次为`3030854`，该语料库总字数为`212741102.0`,据此所计算出的`pmi`=69.00695726310722，
![](https://latex.codecogs.com/svg.latex?\Large&space;pmi=N\times\frac{N(X,Y)}{N(X)N(Y)} ) 

鉴于此处变量只有`total`，直接将上述结果×3得到基于`key的频次累加`的`pmi`大约为`207`

所以是觉得对于`2-gram`来讲`207`和`69`相对于阈值`5`来说都大很多，所以基本差别不大这个意思么？🤣

**Comment by bojone** [comment]
算总数是要每种长度的ngram单独算的，而不是所有2gram、3gram、4gram混合起来算的。

你的统计结果恰好就说明，ngram总数约等于总字数（3倍，因为你把3种ngram混合在一起了）。

事实上，根据（对于某个固定的n）ngram的计算方式： [text[i:i + n] for i in range(len(text) - n + 1)] ，就知道每种ngram的总数约等于字数是显然成立的。

**Comment by TITC** [comment]
> 算总数是要每种长度的ngram单独算的，而不是所有2gram、3gram、4gram混合起来算的。
> 
> 你的统计结果恰好就说明，ngram总数约等于总字数（3倍，因为你把3种ngram混合在一起了）。
> 
> 事实上，根据（对于某个固定的n）ngram的计算方式： [text[i:i + n] for i in range(len(text) - n + 1)] ，就知道每种ngram的总数约等于字数是显然成立的。

`就知道每种ngram的总数约等于字数是显然成立的。`谢谢提醒，明白了👍

**Comment by ghtwht** [comment]
有个疑问，我们计算4-gram是基于我们已经计算好了2-gram以及3-gram基础之上，也就是说我们的2-gram和3-gram也是经过词频和凝固度的过滤，在过滤之后，2-gram和3-gram的总频数也就不存在约等于总次数的情况了，那么我们计算4-gram的凝固度的时候，这个式子也不成立了。
