### ISSUE TITLE
字符集是什么，怎么生成字符集呢

### ISSUE THREAD

**Issue by Chenny0808** [bojone/word-discovery#4]

**Comment by bojone** [comment]
count_grams自动生成字符集。这里的vocab_file仅仅是要保存的文件名，不是现成的文件。

**Comment by Chenny0808** [comment]
corpus_file = 'thucnews.corpus'  # 语料保存的文件名
vocab_file = 'thucnews.chars'  # 字符集
ngram_file = 'thucnews.ngrams'  # ngram集
output_file = 'thucnews.vocab'  # 最后导出的词表
恩恩，这些我明白，都是运行过程中保存的文件

**Comment by Chenny0808** [comment]
终于解决了，可以跑了，linux下安装kenlm倒腾了好久-_-

**Comment by zyjcs** [comment]
> 终于解决了，可以跑了，linux下安装kenlm倒腾了好久-_-

老哥 留个QQ啊  交流一下 谢谢 我的1136899882

**Comment by Chenny0808** [comment]
> > 终于解决了，可以跑了，linux下安装kenlm倒腾了好久-_-
> 
> 老哥 留个QQ啊 交流一下 谢谢 我的1136899882
加你了，大佬
